---
csi:
  enabled: true

injector:
  enabled: true

server:
  standalone:
    enabled: true
    config: |
      ui = true
      plugin_directory = "/vault/plugins"
      
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "file" {
        path = "/vault/data"
      }

  extraInitContainers:
  - name: nats-plugin
    image: "ghcr.io/emm035/nats-secrets-engine@sha256:447da068e8db7a31d6c611464ced2a37070cb4f21df8904649af7c8b3e28519a"
    command: [sh, -c]
    args:
    - cp /nats /vault/plugins/nats
    volumeMounts:
    - name: plugins
      mountPath: /vault/plugins
  
  volumes:
  - name: plugins
    emptyDir: {}
  
  volumeMounts:
  - mountPath: /vault/plugins
    name: plugins
    readOnly: true
